FROM node:16-alpine 
WORKDIR /app
COPY . .
RUN npm install 
WORKDIR /app/apps/agri-mitra

ARG NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_BASE_URL ${NEXT_PUBLIC_BASE_URL}

ARG NEXT_PUBLIC_SOCKET_URL
ENV NEXT_PUBLIC_SOCKET_URL ${NEXT_PUBLIC_SOCKET_URL}

RUN npm run build
ENV NODE_ENV production

EXPOSE 3000
CMD ["npm", "start"]
